services:
  decryptor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: decrypt_media_service
    #ports:
    #  - "8080:8080"
    environment:
      API_TOKEN: ${API_TOKEN}
    restart: unless-stopped
    command: sleep infinity
    networks: 
      nginx-proxy-network:

networks:
  nginx-proxy-network:
    external: true

